### ISSUE TITLE
change default branch to 'feature/first-commit'

### ISSUE THREAD

**Issue by mibamur** [qtkmz/mruby-thumbnail#1]
Hello!

change default branch to 'feature/first-commit' please

**Comment by tk3** [comment]
Hi, @mibamur .

I checked `'feature/first-commit` branch, so I merged to the Master branch.
You use the master branch.
- ref. https://github.com/qtkmz/mruby-thumbnail/pull/2

Thank you!

**Comment by mibamur** [comment]
good
let people see it
